const example_grid_6x6 = {
  grid_width: 6,
  grid_height: 6,
  grid: [
    [
      {
        value: "2",
        cage_num: 1,
        top_border: false,
        bot_border: true,
        left_border: false,
        right_border: false,
      },
      {
        value: "",
        cage_num: 1,
        top_border: false,
        bot_border: true,
        left_border: false,
        right_border: false,
      },
      {
        value: "",
        cage_num: 1,
        top_border: false,
        bot_border: true,
        left_border: false,
        right_border: true,
      },
      {
        value: "4",
        cage_num: 7,
        top_border: false,
        bot_border: false,
        left_border: true,
        right_border: true,
      },
      {
        value: "",
        cage_num: 8,
        top_border: false,
        bot_border: false,
        left_border: true,
        right_border: false,
      },
      {
        value: "2",
        cage_num: 8,
        top_border: false,
        bot_border: false,
        left_border: false,
        right_border: false,
      },
    ],
    [
      {
        value: "",
        cage_num: 2,
        top_border: true,
        bot_border: false,
        left_border: false,
        right_border: false,
      },
      {
        value: "",
        cage_num: 2,
        top_border: true,
        bot_border: false,
        left_border: false,
        right_border: true,
      },
      {
        value: "5",
        cage_num: 7,
        top_border: true,
        bot_border: false,
        left_border: true,
        right_border: false,
      },
      {
        value: "",
        cage_num: 7,
        top_border: false,
        bot_border: true,
        left_border: false,
        right_border: true,
      },
      {
        value: "5",
        cage_num: 8,
        top_border: false,
        bot_border: true,
        left_border: true,
        right_border: false,
      },
      {
        value: "",
        cage_num: 8,
        top_border: false,
        bot_border: false,
        left_border: false,
        right_border: false,
      },
    ],
    [
      {
        value: "",
        cage_num: 2,
        top_border: false,
        bot_border: false,
        left_border: false,
        right_border: false,
      },
      {
        value: "",
        cage_num: 2,
        top_border: false,
        bot_border: true,
        left_border: false,
        right_border: true,
      },
      {
        value: "",
        cage_num: 7,
        top_border: false,
        bot_border: false,
        left_border: true,
        right_border: true,
      },
      {
        value: "",
        cage_num: 6,
        top_border: true,
        bot_border: false,
        left_border: true,
        right_border: false,
      },
      {
        value: "",
        cage_num: 6,
        top_border: true,
        bot_border: false,
        left_border: false,
        right_border: true,
      },
      {
        value: "",
        cage_num: 8,
        top_border: false,
        bot_border: true,
        left_border: true,
        right_border: false,
      },
    ],
    [
      {
        value: "5",
        cage_num: 2,
        top_border: false,
        bot_border: true,
        left_border: false,
        right_border: true,
      },
      {
        value: "",
        cage_num: 3,
        top_border: true,
        bot_border: false,
        left_border: true,
        right_border: true,
      },
      {
        value: "",
        cage_num: 7,
        top_border: false,
        bot_border: true,
        left_border: true,
        right_border: true,
      },
      {
        value: "",
        cage_num: 6,
        top_border: false,
        bot_border: true,
        left_border: true,
        right_border: false,
      },
      {
        value: "",
        cage_num: 6,
        top_border: false,
        bot_border: false,
        left_border: false,
        right_border: true,
      },
      {
        value: "3",
        cage_num: 5,
        top_border: true,
        bot_border: false,
        left_border: true,
        right_border: false,
      },
    ],
    [
      {
        value: "1",
        cage_num: 3,
        top_border: true,
        bot_border: false,
        left_border: false,
        right_border: false,
      },
      {
        value: "",
        cage_num: 3,
        top_border: false,
        bot_border: true,
        left_border: false,
        right_border: true,
      },
      {
        value: "5",
        cage_num: 4,
        top_border: true,
        bot_border: false,
        left_border: true,
        right_border: false,
      },
      {
        value: "2",
        cage_num: 4,
        top_border: true,
        bot_border: false,
        left_border: false,
        right_border: true,
      },
      {
        value: "",
        cage_num: 6,
        top_border: false,
        bot_border: true,
        left_border: true,
        right_border: true,
      },
      {
        value: "",
        cage_num: 5,
        top_border: false,
        bot_border: false,
        left_border: true,
        right_border: false,
      },
    ],
    [
      {
        value: "2",
        cage_num: 3,
        top_border: false,
        bot_border: false,
        left_border: false,
        right_border: true,
      },
      {
        value: "",
        cage_num: 4,
        top_border: true,
        bot_border: false,
        left_border: true,
        right_border: false,
      },
      {
        value: "",
        cage_num: 4,
        top_border: false,
        bot_border: false,
        left_border: false,
        right_border: false,
      },
      {
        value: "3",
        cage_num: 4,
        top_border: false,
        bot_border: false,
        left_border: false,
        right_border: true,
      },
      {
        value: "",
        cage_num: 5,
        top_border: true,
        bot_border: false,
        left_border: true,
        right_border: false,
      },
      {
        value: "1",
        cage_num: 5,
        top_border: false,
        bot_border: false,
        left_border: false,
        right_border: false,
      },
    ],
  ],
};

export default example_grid_6x6;
